[tool.poetry]
name = "organization-catalog-api"
version = "0.1.0"
description = ""
authors = ["Световидов Олег Петрович <osvetovidov@samokat.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
